[build]
  publish = "./dist"
  command = "npm install && npm run build && node ./tsconfig-paths-bootstrap.js"

[context.deploy-preview]
  command = "npm run before-start && npm run server:staging"
  [context.deploy-preview.environment]
  PORT = "4200"